= Notes

== lecture 6

done

=== homework

Домашнее задание Классы Цель: В этом ДЗ вы напишете базовый класс и сделаете
главный модуль, при запуске которого выполняется демонстрация работы всех
классов.

написать базовый класс для средства передвижения, определить у него
общие свойства. Например, вес, грузоподъемность.

Определить общие методы, например “издать звук”

сделать несколько наследников класса. Например: корабль, автомобиль, самолёт.
Перегрузить у них методы, чтобы соответствовать классу.

Также добавить свойства, относящиеся к классу:
водоизмещение, количество колёс, предельная высота и т.д.

базовые классы могут быть реализованы асбстрактными классами
при помощи модуля abc создать более конкретные классы.
Например: “легковой автомобиль”, “парусная лодка” и тд.

Перегрузить общие свойства, а также добавить дополнительные свойства
и методы, разнести все классы и исключения в отдельные модули

добавить методы, которые принимают параметры

добавить в инициализатор и другие методы классов

выкидывание исключения при передаче неподходящих аргументов,
или невыполнении других внутренних условий
(например, если бак пустой, то при попытке “завести” ТС будет выкинуто исключение, что
недостаточно топлива)

можно создать вспомогательные объекты при помощи
датаклассов. Например, объект “двигатель”, у которого есть несколько свойств:
литраж, количество поршней, максимальное количество оборотов… на ваш выбор

сделать главный модуль, при запуске которого выполняется демонстрация работы
всех классов (красивые принты приветствуются)

== lecture 7

1:28:56

== lecture 8

link:https://eforexcel.com/wp/downloads-18-sample-csv-files-data-sets-for-testing-sales/[big csv files]

== Lecture 9

1:00:00

== Lecture 10

1:04:43

== Lecture 11

0:46:00

== Lecture 12

0:17:00

=== homework

Асинхронная работа с сетью

==== Цель

В этом ДЗ вы напишите скрипт.

==== Задача

Написать скрипт, который при помощи асинхронного клиента
обращается к открытому апи (например, jsonplaceholder)
и выводит оттуда информацию

Скрипт для стягивания данных и записи в БД
реализовать в асинхронном виде

. Создать модели для объектов, которые тянутся с открытого апи
. записать вытянутые модели в БД

===== Факультатив

Можно проверить то же самое без асинхронщины...

===== Status

Almost done.

One problem - if photos 5000, then too many open sockets.

Needed to set sockets limitation in ClientSession()
or in another place
or just to limit simultaneously ran coroutines
in wait method (execute wait by chunks by, e.g. 500)

to check - set photos to 5000 again

== Lecture 13

0:15:00
